name: Generate .htaccess File

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      
      - name: Create build directory
        run: mkdir -p build
      
      - name: Generate .htaccess file
        run: ruby ./generate_htaccess.rb data/BEL.yml data/EUE.yml -o build/htaccess
      
      - name: Upload .htaccess as artifact
        uses: actions/upload-artifact@v4
        with:
          name: htaccess-file
          path: build/htaccess
          retention-days: 7
