name: Generate .htaccess File

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      
      - name: Create build directory
        run: mkdir -p build
      
      - name: Generate .htaccess file
        run: ruby ./generate_htaccess.rb data/BEL.yml data/EUE.yml -o build/htaccess
      
      - name: Upload .htaccess as artifact
        uses: actions/upload-artifact@v4
        with:
          name: htaccess-file
          path: build/htaccess
          retention-days: 7

      - name: Create Release
        id: create_release
        if: github.event_name != 'pull_request' # Only create release on push or manual trigger
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: htaccess-${{ github.run_number }}
          release_name: Htaccess Release ${{ github.run_number }}
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        if: github.event_name != 'pull_request' # Only upload to release on push or manual trigger
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/htaccess
          asset_name: .htaccess
          asset_content_type: application/octet-stream
